### ISSUE TITLE
Status of implementation?

### ISSUE THREAD

**Issue by bep** [VonC/asciidocgo#1]
Hey,

There's a discussion going on over at Hugo (https://github.com/spf13/hugo) about adding Asciidoc support.

Having a quick look at your code, I see that there are missing pieces that must be put in place for that to happen.

Is it possible to give a general indicator of how much is missing and if you have any plan of finish this? And if you need any help, with what?

**Comment by VonC** [comment]
Sorry, I missed your comment there.

This was a quick exercise for me to get into Go at the time, I don't intend to complete it anytime soon.
There are a lot of very large ruby files that would need to be translated into Go, and I would estimate the current implementation to be only 10-15% of the all asciidoctor project.

That project would be better off if cloned and re-created (instead of forked).
